# Generated by Django 2.1.8 on 2019-04-11 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('insta_id', models.CharField(max_length=255)),
                ('followers', models.IntegerField()),
                ('insta_link', models.CharField(max_length=255)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('styles', models.ManyToManyField(to='core.Style')),
                ('tags', models.ManyToManyField(to='core.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
