# Generated by Django 2.1.8 on 2019-04-11 16:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_influencer'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=core.models.influencer_image_file_path),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
